[workspace]
members = [
    "solar-system-catalog",
    "solar-system-catalog-client-sdk",
    "solar-system-catalog-server-sdk",
]
exclude = [
    "model/build/codegen/solar-system-catalog-server-sdk/rust-server-codegen",
    "model/build/codegen/solar-system-catalog-client-sdk/rust-codegen",
]
